CREATE TYPE "role" AS ENUM ('admin', 'owner', 'user');
CREATE TABLE "users" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "company" TEXT NOT NULL,
    "role" role NOT NULL,
    "password_hash" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_users_by_email" ON "users" ("email");
